# Files in the project. Make sure the first file is the top module
VHD = uprogCPU.vhd

# Design constraints file
XDC = Basys3.xdc

# Testbench file
TBF = uprogCPU_tb.vhd

# Include Makefile utilities
include /courses/TSEA83/bin/util.mk

